resources:
  web:
    replicas: 2
    storage: 10Gi
    requests:
      cpu: 135m
      memory: 800Mi
    limits:
      memory: 800Mi

  collaboration:
    requests:
      cpu: 135m
      memory: 800Mi
    limits:
      memory: 800Mi

  redis:
    storage: 2Gi
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

  sync:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

  init:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

  exporter:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

  database:
    storage: 10Gi
    replicas: 3
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi

  blackbox:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
