images:
  web:
    version: "1.4.0"
  init:
    version: "1.2.1"
  sync:
    version: "2.0.1"
  exporter:
    version: "1.4.2"
  redis:
    version: "8.4.0"
  blackbox:
    version: "0.28.0"

resources:
  web:
    replicas: 1
    storage: 5Gi
    requests:
      cpu: 295m
      memory: 750Mi
    limits:
      memory: 750Mi

  collaboration:
    requests:
      cpu: 295m
      memory: 750Mi
    limits:
      memory: 750Mi

  redis:
    storage: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

  sync:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

  init:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

  exporter:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      memory: 64Mi

  database:
    storage: 10Gi
    replicas: 2
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

  blackbox:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
