---
- name: Deploy PostgreSQL
  hosts: all
  roles:
    - postgres
  tags: [postgres]

- name: Deploy Redis
  hosts: all
  roles:
    - redis
  tags: [redis]

- name: Deploy monitoring
  hosts: all
  roles:
    - monitoring
  tags: [monitoring]

- name: Deploy Outline
  hosts: all
  roles:
    - outline
  tags: [outline]
