---
- name: Create collaboration Service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app.name }}-collaboration"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: collaboration
      spec:
        selector:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: collaboration
        ports:
          - name: http
            port: 80
            targetPort: 3000

- name: Create collaboration Route
  kubernetes.core.k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ app.name }}-collaboration"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: collaboration
          route: private
        annotations:
          route.openshift.io/timeout: 3600s
      spec:
        host: "{{ app.domain }}"
        path: /collaboration
        to:
          kind: Service
          name: "{{ app.name }}-collaboration"
        port:
          targetPort: http
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect

- name: Deploy collaboration service
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app.name }}-collaboration"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: collaboration
      spec:
        replicas: 1
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
        selector:
          matchLabels:
            app.kubernetes.io/name: "{{ app.name }}"
            app.kubernetes.io/component: collaboration
        template:
          metadata:
            labels:
              app.kubernetes.io/name: "{{ app.name }}"
              app.kubernetes.io/component: collaboration
          spec:
            containers:
              - name: collaboration
                image: "{{ registry }}/outline:{{ images.web.version }}"
                imagePullPolicy: Always
                ports:
                  - containerPort: 3000
                env:
                  - name: YARN_CACHE_FOLDER
                    value: /tmp/.yarn-cache
                  - name: URL
                    value: "{{ app.url }}"
                  - name: WEB_CONCURRENCY
                    value: "1"
                envFrom:
                  - secretRef:
                      name: "{{ app.name }}-secrets"
                command: ["/bin/sh", "-c"]
                args: ["yarn start --services=collaboration"]
                resources:
                  requests:
                    cpu: "{{ resources.collaboration.requests.cpu }}"
                    memory: "{{ resources.collaboration.requests.memory }}"
                  limits:
                    memory: "{{ resources.collaboration.limits.memory }}"
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 20
                  periodSeconds: 10
                livenessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 20
                  periodSeconds: 30
                volumeMounts:
                  - name: yarn-cache
                    mountPath: /tmp/.yarn-cache
                  - name: uploads
                    mountPath: /var/lib/outline/data
            volumes:
              - name: yarn-cache
                emptyDir: {}
              - name: uploads
                persistentVolumeClaim:
                  claimName: "{{ app.name }}-uploads"
            imagePullSecrets:
              - name: "{{ pull_secret }}"
