---
- name: Deploy secrets
  ansible.builtin.include_tasks:
    file: secrets.yml
    apply:
      tags: [outline.secrets]
  tags: [outline.secrets]

- name: Deploy web application
  ansible.builtin.include_tasks:
    file: web.yml
    apply:
      tags: [outline.web]
  tags: [outline.web]

- name: Deploy collaboration service
  ansible.builtin.include_tasks:
    file: collaboration.yml
    apply:
      tags: [outline.collaboration]
  tags: [outline.collaboration]

- name: Deploy init job
  ansible.builtin.include_tasks:
    file: init.yml
    apply:
      tags: [outline.init]
  tags: [outline.init]

- name: Deploy syncer
  ansible.builtin.include_tasks:
    file: sync.yml
    apply:
      tags: [outline.sync]
  tags: [outline.sync]
