---
- name: Create exporter Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app.name }}-exporter"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: exporter
      spec:
        replicas: 1
        selector:
          matchLabels:
            app.kubernetes.io/name: "{{ app.name }}"
            app.kubernetes.io/component: exporter
        template:
          metadata:
            labels:
              app.kubernetes.io/name: "{{ app.name }}"
              app.kubernetes.io/component: exporter
          spec:
            containers:
              - name: exporter
                image: "{{ registry }}/exporter:{{ images.exporter.version }}"
                imagePullPolicy: Always
                ports:
                  - containerPort: 9877
                    name: metrics
                env:
                  - name: OUTLINE_API_URL
                    value: "{{ app.url }}"
                  - name: OUTLINE_API_KEY
                    valueFrom:
                      secretKeyRef:
                        name: "{{ app.name }}-api-key-monitoring"
                        key: API_KEY
                resources:
                  requests:
                    cpu: "{{ resources.exporter.requests.cpu }}"
                    memory: "{{ resources.exporter.requests.memory }}"
                  limits:
                    memory: "{{ resources.exporter.limits.memory }}"
                readinessProbe:
                  httpGet:
                    path: /healthz
                    port: metrics
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: metrics
            imagePullSecrets:
              - name: "{{ pull_secret }}"

- name: Create PodMonitor
  kubernetes.core.k8s:
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PodMonitor
      metadata:
        name: "{{ app.name }}-exporter"
        namespace: "{{ inventory_hostname }}"
        labels:
          app.kubernetes.io/name: "{{ app.name }}"
          app.kubernetes.io/component: exporter
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: "{{ app.name }}"
            app.kubernetes.io/component: exporter
        inventory_hostnameSelector:
          matchNames:
            - "{{ inventory_hostname }}"
        podMetricsEndpoints:
          - port: metrics
            interval: 2m
            path: /metrics
            scrapeTimeout: 25s
