postgres:
  backup:
    schedule: "0 0 2 * * *"
    retention: "30d"
    owner_reference: self
  cluster:
    name: postgres-cluster
  service:
    read_write: postgres-cluster-rw
    read_only: postgres-cluster-ro
