resources:
  test:
    web:
      replicas: 1
      requests:
        cpu: 295m
        memory: 590Mi
      limits:
        memory: 590Mi
    collaboration:
      requests:
        cpu: 295m
        memory: 590Mi
      limits:
        memory: 590Mi
    redis:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
    sync:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
    init:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
    exporter:
      requests:
        cpu: 5m
        memory: 16Mi
      limits:
        memory: 32Mi
  prod:
    web:
      replicas: 2
      requests:
        cpu: 135m
        memory: 800Mi
      limits:
        memory: 800Mi
    collaboration:
      requests:
        cpu: 135m
        memory: 800Mi
      limits:
        memory: 800Mi
    redis:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
    sync:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
    init:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
    exporter:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
